export const API_URL = `${process.env.API_ORIGIN}/api/weblarek`;
export const CDN_URL = `${process.env.API_ORIGIN}/content/weblarek`;

export enum Events {
	SET_PRODUCTS = 'gallery:add products',
	PREVIEW_CHANGE = 'preview:change',
	TAKE_PRODUCT = 'basket:add product',
	OPEN_BASKET = 'basket:open',
	REMOVE_PRODUCT = 'basket:delete product',
	CLEAR_BASKET = 'basket:clear',
	CREATE_ORDER = 'order:create',
	ORDER_SUBMIT = 'order:submit',
	ACCEPT_ORDER = 'order:accept',
	SUCCESS_SUMBIT = 'success:submit',
	MODAL_WINDOW_OPEN = 'modal:open',
	MODAL_WINDOW_CLOSE = 'modal:close',
}

export const settings = {
	pageSelector: '.page',
	pageSettings: {
		productsInBusket: '.header__basket-counter',
		wrapper: '.page__wrapper',
		products: '.gallery',
		basket: '.header__basket',
	},
	productInCatalogSelector: '.gallery__item',
	productInCatalogTemplate: '#card-catalog',
	productInCatalogSettings: {
		category: '.card__category',
		title: '.card__title',
		image: '.card__image',
		price: '.card__price',
		button: '.gallery__item',
	},
	productFullSelector: '.card_full',
	productFullTemplate: '#card-preview',
	productFullSettings: {
		title: '.card__title',
		image: '.card__image',
		category: '.card__category',
		description: '.card_text',
		price: '.card__price',
		button: '.button',
	},
	basketSelector: '.basket',
	basketTemplate: '#basket',
	basketSettings: {
		title: '.modal__title',
		items: '.basket__list',
		total: '.basket__price',
		button: '.basket__button',
	},
	basketItemSelector: '.card_compact',
	basketItemTemplate: '#card-basket',
	basketItemSettings: {
		id: '.basket__item-index',
		title: '.card__title',
		price: '.card__price',
		button: '.basket__item-delete',
	},
	orderSelector: '.order',
	orderTemplate: '#order',
	orderSettings: {
		address: 'input[name="address"]',
		title: '.card__title',
		buttonCardName: 'button[name="card"]',
		buttonCashName: 'button[name="cash"]',
		buttonSubmit: '.order__button',
	},
	contactsSelector: '.contacts',
	contactsTemplate: '#contacts',
	contactsSettings: {
		email: 'input[name="email"]',
		phone: 'input[name="phone"]',
		button: '.button',
	},
	successSelector: '.order-success',
	successTemplate: '#success',
	successSettings: {
		total: '.order-success__description',
		button: '.order-success__close',
	},
	modalTemplate: '#modal-container',
	modalSettings: {
		content: '.modal__content',
		button: '.modal__close',
	},
	errorField: '.form__errors',
};
